'use client';

import { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

// ── Translation dictionaries ────────────────────────────────────────────────

const en: Record<string, string> = {
  // Nav
  'nav.programs': 'Programs',
  'nav.howItWorks': 'How It Works',
  'nav.transformations': 'Transformations',
  'nav.marketplace': 'Marketplace',
  'nav.pricing': 'Pricing',
  'nav.about': 'About',
  'nav.contact': 'Contact',
  'nav.dashboard': 'Dashboard',
  'nav.account': 'Account',
  'nav.soon': 'Soon',

  // Footer
  'footer.tagline': 'Premium fitness coaching with personalized meal plans. Transform your body, elevate your life.',
  'footer.quickLinks': 'Quick Links',
  'footer.aboutUs': 'About Us',
  'footer.ourPrograms': 'Our Programs',
  'footer.muscleBuilding': 'Muscle Building',
  'footer.fatLoss': 'Fat Loss',
  'footer.summerBody': 'Summer Body',
  'footer.workoutPlan': 'Workout Plan',
  'footer.mealPlan': 'Meal Plan',
  'footer.getInTouch': 'Get in Touch',
  'footer.email': 'Email',
  'footer.whatsapp': 'WhatsApp',
  'footer.messageUs': 'Message Us',
  'footer.freeConsultation': 'Free Consultation',
  'footer.allRightsReserved': 'All rights reserved.',
  'footer.privacyPolicy': 'Privacy Policy',
  'footer.termsOfService': 'Terms of Service',
  'footer.language': 'Language',
  'footer.premiumCoaching': 'Premium coaching',
  'footer.noFreeTrials': 'No free trials',
  'footer.transparentPricing': 'Transparent pricing',
  'footer.realResults': 'Real results',

  // Hero
  'hero.headline1': 'UNLEASH YOUR',
  'hero.headline2': 'POTENTIAL',
  'hero.subtext': 'Join a community where goals are crushed, strength is built, and potential becomes power.',
  'hero.cta': 'Get Started',

  // Programs page
  'programs.badge': 'Our Programs',
  'programs.title': 'Choose Your',
  'programs.titleHighlight': 'Path',
  'programs.subtitle': 'Every program is built around you — your body, your goals, your lifestyle. Start with a free consultation and we\'ll match you to the right plan.',
  'programs.whatsIncluded': "What's included",
  'programs.idealFor': 'Ideal for',
  'programs.startProgram': 'Start This Program',
  'programs.notSure': 'Not sure which program is right for you?',
  'programs.bookConsultation': 'Book a Free Consultation',

  // Program names
  'program.muscleBuilding.name': 'Muscle Building',
  'program.muscleBuilding.tagline': 'Build lean, lasting size',
  'program.muscleBuilding.description': 'A structured hypertrophy program designed to add lean muscle through progressive overload, precision nutrition, and weekly coach adjustments. Every rep, every meal — engineered for growth.',
  'program.muscleBuilding.ideal': 'Those who want to build size, improve definition, and increase strength over a sustained period.',
  'program.muscleBuilding.i1': 'Custom hypertrophy workout plan (5 days/week)',
  'program.muscleBuilding.i2': 'High-protein meal plan tailored to your macros',
  'program.muscleBuilding.i3': 'Weekly 1-on-1 check-ins with your coach',
  'program.muscleBuilding.i4': 'Progressive overload tracking built-in',
  'program.muscleBuilding.i5': 'Supplement guidance included',

  'program.fatLoss.name': 'Fat Loss',
  'program.fatLoss.tagline': 'Burn fat, keep muscle',
  'program.fatLoss.description': "A caloric-deficit program that preserves muscle while systematically reducing body fat. Combines structured cardio, strength training, and a precision nutrition plan that doesn't feel like a diet.",
  'program.fatLoss.ideal': 'Anyone looking to reduce body fat, improve body composition, and build sustainable healthy habits.',
  'program.fatLoss.i1': 'Fat-loss focused workout plan',
  'program.fatLoss.i2': 'Caloric deficit meal plan with macro targets',
  'program.fatLoss.i3': 'Weekly weigh-in and body check reviews',
  'program.fatLoss.i4': 'Cardio protocol adjusted weekly',
  'program.fatLoss.i5': 'Mindset & accountability coaching',

  'program.summerBody.name': 'Summer Body',
  'program.summerBody.tagline': '12 weeks to your best shape',
  'program.summerBody.description': 'A deadline-driven transformation program. Combines fat loss and muscle toning for a lean, athletic physique — ready for summer. Designed for real results in a realistic timeframe.',
  'program.summerBody.ideal': 'People who have a specific timeframe and want a complete body transformation program.',
  'program.summerBody.i1': 'Toning + fat-loss hybrid workout plan',
  'program.summerBody.i2': 'Clean-eating meal plan (no starvation)',
  'program.summerBody.i3': 'Body transformation progress tracking',
  'program.summerBody.i4': 'Weekly photo check-ins reviewed by coach',
  'program.summerBody.i5': 'Motivation & accountability system',

  'program.workoutOnly.name': 'Workout Plan Only',
  'program.workoutOnly.tagline': 'Structured training, no meal plan',
  'program.workoutOnly.description': 'A fully personalized workout plan without the meal planning component. Perfect for those who already have their nutrition dialled in but want expert-designed training structure.',
  'program.workoutOnly.ideal': 'Those who have an existing nutrition routine and want a professional training structure to follow.',
  'program.workoutOnly.i1': 'Fully custom workout plan',
  'program.workoutOnly.i2': 'Day-by-day exercise schedule',
  'program.workoutOnly.i3': 'Sets, reps, rest & technique notes',
  'program.workoutOnly.i4': 'Exercise image/video references',
  'program.workoutOnly.i5': 'Monthly plan updates',

  'program.mealOnly.name': 'Meal Plan Only',
  'program.mealOnly.tagline': 'Precision nutrition, no guesswork',
  'program.mealOnly.description': 'A fully customized meal plan built around your goals, body metrics, and dietary preferences. No guesswork — just a clear, delicious eating structure that works.',
  'program.mealOnly.ideal': 'Those who train independently and want expert nutrition to complement their existing workout routine.',
  'program.mealOnly.i1': 'Custom meal plan (breakfast, lunch, snack, dinner)',
  'program.mealOnly.i2': 'Macro & calorie targets per meal',
  'program.mealOnly.i3': 'Dietary restrictions fully respected',
  'program.mealOnly.i4': 'Grocery-friendly food choices',
  'program.mealOnly.i5': 'Monthly meal plan refreshes',

  // About page
  'about.badge': 'About OMR+',
  'about.title': 'Premium Coaching,',
  'about.titleHighlight': 'Real Results',
  'about.subtitle': 'OMR+ is a premium fitness coaching platform built for people who are serious about transforming their bodies — with expert guidance, not guesswork.',
  'about.mission.title': 'Our Mission',
  'about.mission.body': 'To deliver world-class fitness coaching that\'s accessible, personalized, and built around real results — not empty promises.',
  'about.approach.title': 'Our Approach',
  'about.approach.body': 'Every client receives a completely personalized plan — tailored workouts, custom meal plans, and weekly check-ins with a dedicated coach.',
  'about.values.title': 'Our Values',
  'about.values.b1': 'Personalization over generic plans',
  'about.values.b2': 'Transparency & honest communication',
  'about.values.b3': 'Results-driven accountability',
  'about.values.b4': 'Premium quality in everything we do',
  'about.cta': 'Start Your Transformation',

  // Contact page
  'contact.badge': 'Contact Us',
  'contact.title': "Let's",
  'contact.titleHighlight': 'Talk',
  'contact.subtitle': 'Have a question or ready to start? Reach out and we\'ll get back to you.',
  'contact.whatsapp.title': 'WhatsApp',
  'contact.whatsapp.desc': 'Message us directly for the fastest response.',
  'contact.whatsapp.btn': 'Message on WhatsApp',
  'contact.email.title': 'Email',
  'contact.email.desc': 'Send us a message and we\'ll reply within 24 hours.',
  'contact.form.title': 'Send a Message',
  'contact.form.name': 'Full Name',
  'contact.form.namePlaceholder': 'Your name',
  'contact.form.email': 'Email Address',
  'contact.form.emailPlaceholder': 'your@email.com',
  'contact.form.message': 'Message',
  'contact.form.messagePlaceholder': 'How can we help you?',
  'contact.form.submit': 'Send Message',
  'contact.form.sending': 'Sending…',
  'contact.form.success': 'Message sent! We\'ll be in touch soon.',

  // Marketplace page
  'marketplace.badge': 'Marketplace',
  'marketplace.title': 'Premium Supplements',
  'marketplace.titleHighlight': '& More',
  'marketplace.subtitle': 'Hand-picked supplements, nutrition products, and expert resources to support your fitness journey.',
  'marketplace.comingSoon': 'Coming Soon',
  'marketplace.comingSoonTitle': 'Store Opening Soon',
  'marketplace.comingSoonDesc': 'We\'re curating the best supplements and nutrition products for you. Check back soon.',
  'marketplace.notifyBtn': 'Notify Me',

  // How It Works section
  'hiw.badge': 'How It Works',
  'hiw.title': 'Your Journey to',
  'hiw.titleHighlight': 'Transformation',
  'hiw.step1.title': 'Free Consultation',
  'hiw.step1.desc': 'Book a free consultation with our team. We\'ll assess your goals, lifestyle, and fitness level to match you with the right program.',
  'hiw.step2.title': 'Get Your Plan',
  'hiw.step2.desc': 'Receive a fully customized workout and meal plan, tailored specifically to your body, goals, and schedule.',
  'hiw.step3.title': 'Coach Support',
  'hiw.step3.desc': 'Stay connected with your dedicated coach. Weekly check-ins, plan adjustments, and real-time messaging keep you on track.',
  'hiw.step4.title': 'Track Progress',
  'hiw.step4.desc': 'Log your progress, upload body checks, and watch your transformation unfold with data-driven insights.',

  // Transformations section
  'trans.badge': 'Transformations',
  'trans.title': 'Real People,',
  'trans.titleHighlight': 'Real Results',
  'trans.subtitle': 'Privacy-protected client transformations. Results vary by individual commitment and program.',
  'trans.disclaimer': 'Client identities protected. Results shown with permission.',
  'trans.verified': 'Verified Result',
  'trans.more': 'Hundreds more stories waiting to be told',
  'trans.viewAll': 'View All Transformations',
  'trans.t1.label': 'lost',
  'trans.t1.program': 'Fat Loss',
  'trans.t1.duration': '12 weeks',
  'trans.t1.change': 'Body composition improved significantly. Consistent training and tailored nutrition made the difference.',
  'trans.t2.label': 'gained',
  'trans.t2.program': 'Muscle Building',
  'trans.t2.duration': '16 weeks',
  'trans.t2.change': 'Strength increased by 40%. Progressive overload and precision meal planning built a foundation that lasts.',
  'trans.t3.label': 'confidence',
  'trans.t3.program': 'Summer Body',
  'trans.t3.duration': '12 weeks',
  'trans.t3.change': 'More energy, better posture, and a physique to be proud of — achieved through consistency and guidance.',
  'trans.stat1': 'Active Members',
  'trans.stat2': 'Success Rate',
  'trans.stat3': 'Avg. Months',
  'trans.stat4': 'Check-ins',

  // Pricing section
  'pricing.badge': 'Pricing',
  'pricing.title': 'Simple,',
  'pricing.titleHighlight': 'Transparent Pricing',
  'pricing.subtitle': 'No hidden fees. No free trials. Choose the plan that fits your goals.',
  'pricing.perMonth': '/month',
  'pricing.getStarted': 'Get Started',
  'pricing.popular': 'Most Popular',
  'pricing.consultation': 'Book Free Consultation',
  'pricing.footer1': 'All prices listed in Saudi Riyal (SAR). Pricing is managed by the admin and subject to change.',
  'pricing.footer2': 'Not sure which plan? Book your free consultation — no commitment required.',
  'pricing.plan1.name': 'Plan Only',
  'pricing.plan1.tagline': 'Self-paced structure',
  'pricing.plan1.desc': 'Get a fully customized meal or workout plan built around your body, goals, and lifestyle.',
  'pricing.plan1.cta': 'Get Started',
  'pricing.plan1.f1': 'Custom meal plan or workout plan',
  'pricing.plan1.f2': 'Personalized to your goals',
  'pricing.plan1.f3': 'Dietary restrictions included',
  'pricing.plan1.f4': 'Weekly plan updates',
  'pricing.plan1.f5': 'PDF download access',
  'pricing.plan2.name': 'Full Coaching',
  'pricing.plan2.tagline': 'Most chosen program',
  'pricing.plan2.desc': 'Complete coaching experience — custom plans, weekly check-ins, and direct access to your trainer.',
  'pricing.plan2.cta': 'Start Coaching',
  'pricing.plan2.f1': 'Custom meal plan + workout plan',
  'pricing.plan2.f2': 'Dedicated personal trainer',
  'pricing.plan2.f3': 'Weekly 1-on-1 check-ins',
  'pricing.plan2.f4': 'Real-time messaging with coach',
  'pricing.plan2.f5': 'Progress tracking & adjustments',
  'pricing.plan2.f6': 'InBody analysis support',
  'pricing.plan2.f7': 'Priority plan updates',
  'pricing.plan3.name': 'Elite',
  'pricing.plan3.tagline': 'Maximum results',
  'pricing.plan3.desc': 'The full OMR+ experience — elite coaching with premium add-ons for those who want the best.',
  'pricing.plan3.cta': 'Go Elite',
  'pricing.plan3.f1': 'Everything in Full Coaching',
  'pricing.plan3.f2': 'Unlimited coach messages',
  'pricing.plan3.f3': 'Bi-weekly video consultations',
  'pricing.plan3.f4': 'Supplement guidance',
  'pricing.plan3.f5': 'Competition prep support',
  'pricing.plan3.f6': 'Priority onboarding',

  // Consultation CTA
  'cta.title': 'Ready to Transform?',
  'cta.subtitle': 'Book your free consultation today and take the first step toward the body you deserve.',
  'cta.btn': 'Book Free Consultation',

  // Testimonials
  'testimonials.badge': 'Testimonials',
  'testimonials.title': 'What Our',
  'testimonials.titleHighlight': 'Members Say',

  // Login page
  'login.memberPortal': 'Member Portal',
  'login.title': 'Welcome Back',
  'login.subtitle': 'Sign in to access your coaching dashboard',
  'login.email': 'Email Address',
  'login.emailPlaceholder': 'you@example.com',
  'login.password': 'Password',
  'login.forgotPassword': 'Forgot password?',
  'login.signIn': 'Sign In',
  'login.signingIn': 'Signing in…',
  'login.noAccount': "Don't have an account?",
  'login.createOne': 'Create one',
  'login.secureLogin': 'Secure login',
  'login.dataPrivate': 'Your data is private',

  // Signup page
  'signup.memberPortal': 'New Member',
  'signup.title': 'Create Your Account',
  'signup.subtitle': 'Join OMR+ and start your transformation',
  'signup.fullName': 'Full Name',
  'signup.fullNamePlaceholder': 'Your full name',
  'signup.email': 'Email Address',
  'signup.emailPlaceholder': 'you@example.com',
  'signup.password': 'Password',
  'signup.passwordPlaceholder': '••••••••',
  'signup.confirmPassword': 'Confirm Password',
  'signup.confirmPlaceholder': '••••••••',
  'signup.createAccount': 'Create Account',
  'signup.creating': 'Creating account…',
  'signup.haveAccount': 'Already have an account?',
  'signup.signIn': 'Sign in',
  'signup.secureSignup': 'Secure signup',
  'signup.dataPrivate': 'Your data is private',

  // Dashboard Shell
  'dash.memberPortal': 'Member Portal',
  'dash.coachPortal': 'Coach Portal',
  'dash.adminPanel': 'Admin Panel',
  'dash.signOut': 'Sign Out',
  'dash.backToSite': 'Back to site',

  // Client Dashboard
  'client.overview': 'Overview',
  'client.mealPlan': 'Meal Plan',
  'client.workoutPlan': 'Workout Plan',
  'client.progress': 'Progress',
  'client.messages': 'Messages',
  'client.subscription': 'Subscription',
  'client.welcome': 'Welcome back',
  'client.yourCoach': 'Your Coach',
  'client.noCoach': 'No coach assigned yet',
  'client.activePlan': 'Active Plan',
  'client.loading': 'Loading…',
  'client.noMealPlan': 'No meal plan assigned yet',
  'client.noWorkoutPlan': 'No workout plan assigned yet',
  'client.watchVideo': 'Watch',

  // Coach Dashboard
  'coach.clients': 'Clients',
  'coach.mealBuilder': 'Meal Builder',
  'coach.workoutBuilder': 'Workout Builder',
  'coach.progress': 'Progress',
  'coach.messages': 'Messages',
  'coach.welcome': 'Welcome back, Coach',
  'coach.myClients': 'My Clients',
  'coach.assignedClients': 'Assigned Clients',

  // Admin Dashboard
  'admin.overview': 'Overview',
  'admin.users': 'Users',
  'admin.coaches': 'Coaches',
  'admin.subscriptions': 'Subscriptions',
  'admin.marketplace': 'Marketplace',
  'admin.pricing': 'Pricing',
  'admin.videos': 'Videos',
  'admin.analytics': 'Analytics',
  'admin.chat': 'Chat',
  'admin.welcome': 'Welcome, Admin',

  // Admin Dashboard — extended labels
  'admin.platformOverview': 'Platform Overview',
  'admin.platformSubtitle': 'Full control of the OMR+ platform.',
  'admin.totalMembers': 'Total Members',
  'admin.registeredClients': 'Registered clients',
  'admin.activeCoaches': 'Active Coaches',
  'admin.platformTrainers': 'Platform trainers',
  'admin.activeSubscriptions': 'Active Subscriptions',
  'admin.payingMembers': 'Paying members',
  'admin.monthlyRevenue': 'Monthly Revenue',
  'admin.activeSubscriptionsLabel': 'Active subscriptions',
  'admin.recentMembers': 'Recent Members',
  'admin.viewAll': 'View All',
  'admin.manage': 'Manage',
  'admin.noMembers': 'No members yet',
  'admin.noCoaches': 'No coaches yet',
  'admin.clients': 'clients',
  'admin.statusActive': 'active',
  'admin.statusFree': 'free',
  'admin.member': 'MEMBER',
  'admin.status': 'STATUS',
  'admin.onboarded': 'ONBOARDED',
  'admin.coach': 'COACH',
  'admin.joined': 'JOINED',
  'admin.unnamed': 'Unnamed',
  'admin.yes': 'Yes',
  'admin.no': 'No',
  'admin.noCoachAssigned': '—',
  'admin.saving': 'Saving…',
  'admin.save': 'Save',
  'admin.cancel': 'Cancel',
  'admin.addPlan': '+ Add Plan',
  'admin.editPlan': 'Edit Plan',
  'admin.newPlan': 'New Plan',
  'admin.delete': 'Delete',
  'admin.publish': 'Publish',
  'admin.unpublish': 'Unpublish',
  'admin.createCoach': 'Create Coach Account',
  'admin.assignCoach': 'Assign Coach',
  'admin.usersTab': 'Users',
  'admin.loading': 'Loading…',
  'admin.noData': 'No data available',

  // Client Dashboard — extended labels
  'client.overviewTitle': 'Overview',
  'client.welcomeBack': 'Welcome back',
  'client.subscriptionActive': 'Active',
  'client.subscriptionExpired': 'Expired',
  'client.noSubscription': 'No active subscription',
  'client.upgradeNow': 'Upgrade Now',
  'client.logWeight': 'Log Weight',
  'client.weightKg': 'Weight (kg)',
  'client.notes': 'Notes (optional)',
  'client.saveEntry': 'Save Entry',
  'client.saving': 'Saving…',
  'client.progressHistory': 'Progress History',
  'client.noProgress': 'No progress logged yet',
  'client.sendMessage': 'Send',
  'client.messagePlaceholder': 'Type a message…',
  'client.noMessages': 'No messages yet',
  'client.online': 'Online',

  // Coach Dashboard — extended labels
  'coach.overview': 'Overview',
  'coach.loading': 'Loading…',
  'coach.noClients': 'No clients assigned yet',
  'coach.selectClient': 'Select a client to start chatting',
  'coach.messagePlaceholder': 'Type a message…',
  'coach.send': 'Send',
  'coach.noMessages': 'No messages yet. Say hello!',
  'coach.onboarded': 'Onboarded',
  'coach.notOnboarded': 'Not onboarded',
  'coach.active': 'active',

  // Home Programs Section
  'home.programs.badge': 'Our Programs',
  'home.programs.title': 'Choose Your',
  'home.programs.titleHighlight': 'Path',
  'home.programs.subtitle': 'Pick the program that matches your goals. All plans include personalized support.',
  'home.programs.getStarted': 'Get Started',
  'home.programs.viewAll': 'View All Programs',
  'home.programs.viewAllSub': 'Want to see all programs in detail?',
  'home.programs.muscleBuilding': 'Muscle Building',
  'home.programs.muscleBuilding.desc': 'Build lean muscle mass with progressive strength training and high-protein meal plans.',
  'home.programs.fatLoss': 'Fat Loss',
  'home.programs.fatLoss.desc': 'Sustainable fat loss through structured nutrition and cardio-strength combination workouts.',
  'home.programs.summerBody': 'Summer Body',
  'home.programs.summerBody.desc': 'Transform in 12 weeks with our scientifically-backed summer body program.',
  'home.programs.workoutPlan': 'Workout Plan',
  'home.programs.workoutPlan.desc': 'Structured workout plans without meal planning. Perfect for those with their own diet.',
  'home.programs.mealPlan': 'Meal Plan',
  'home.programs.mealPlan.desc': 'Get personalized meal plans tailored to your goals and dietary preferences.',

  // Testimonials Section — extended
  'testimonials.subtitle': 'Real feedback from members who committed to the process and came out the other side transformed.',
  'testimonials.m1.quote': 'OMR+ completely transformed my journey. The personalized meal plans and trainer support made every week feel structured and achievable. Lost 20kg and gained a completely different relationship with my body.',
  'testimonials.m1.role': 'Fat Loss Program',
  'testimonials.m2.quote': 'The professionalism here is unmatched. My trainer adjusted my program every single week based on real data. It never felt like a generic plan — it felt built just for me.',
  'testimonials.m2.role': 'Muscle Building Program',
  'testimonials.m3.quote': 'Skeptical at first, but within six weeks the results were undeniable. The coaching, the accountability, and the precision of the nutrition plan — nothing else compares.',
  'testimonials.m3.role': 'Summer Body Program',
  'testimonials.m4.quote': "Worth every riyal. When I wanted to quit at week four, my coach was there with the right adjustment and the right words. Best investment I've made in myself.",
  'testimonials.m4.role': 'Elite Coaching',

  // Admin — Subscriptions tab
  'admin.subscriptionsTitle': 'Subscriptions',
  'admin.totalSubscriptions': 'total subscriptions',
  'admin.filterAll': 'All',
  'admin.filterActive': 'Active',
  'admin.filterCancelled': 'Cancelled',
  'admin.filterExpired': 'Expired',
  'admin.colPlan': 'Plan',
  'admin.colAmount': 'Amount',
  'admin.colStart': 'Start',
  'admin.colExpires': 'Expires',
  'admin.noSubscriptions': 'No subscriptions found',

  // Admin — Marketplace tab
  'admin.marketplaceTitle': 'Marketplace',
  'admin.marketplaceSub': 'Manage products and ebooks',
  'admin.addProduct': '+ Add Product',
  'admin.activeInStore': 'Active (visible in store)',

  // Admin — Pricing tab
  'admin.pricingTitle': 'Pricing Plans',
  'admin.pricingSubtitle': 'Create plans with Stripe Price IDs — publish to show them on the site.',

  // Admin — Chat tab
  'admin.chatTitle': 'Chat Threads',
  'admin.chatSubtitle': 'All client–coach conversations',
  'admin.colClient': 'Client',
  'admin.colCoach': 'Coach',
  'admin.colStarted': 'Started',
  'admin.viewThread': 'View',
  'admin.noConversations': 'No conversations yet',
  'admin.noConversationsSub': 'Chat threads appear here once clients and coaches start messaging.',

  // Admin — Videos tab
  'admin.videosTitle': 'Workout Videos',
  'admin.uploadVideo': 'Upload Video',
  'admin.uploading': 'Uploading',
  'admin.processing': 'Processing…',
  'admin.uploadingVideo': 'Uploading video…',
  'admin.processingCloudinary': 'Processing on Cloudinary…',

  // Admin — Analytics tab
  'admin.analyticsTitle': 'Analytics',
  'admin.analyticsSub': 'Platform performance summary',
  'admin.totalRegistered': 'Total Registered',
  'admin.allTimeSignups': 'All-time signups',
  'admin.activeSubscribers': 'Active Subscribers',
  'admin.currentlyPaying': 'Currently paying',
  'admin.churned': 'Churned',
  'admin.cancelledSubscriptions': 'Cancelled subscriptions',
  'admin.onboardingRate': 'Onboarding Rate',
  'admin.completedQuestionnaire': 'Completed questionnaire',
  'admin.fromActivePlans': 'From active plans',
  'admin.avgRevenueUser': 'Avg Revenue/User',
  'admin.perRegisteredClient': 'Per registered client',
  'admin.newMembers': 'New Members',
  'admin.last6Months': 'Last 6 months',
  'admin.revenueSAR': 'Revenue (SAR)',
  'admin.subscriptionBreakdown': 'Subscription Breakdown',
  'admin.statusDistribution': 'Status distribution',
  'admin.statusCancelled': 'Cancelled',
  'admin.statusExpired': 'Expired',
  'admin.statusPastDue': 'Past Due',

  // Coach Dashboard — additional UI strings
  'coach.overview.summary': "Here's a summary of your coaching activity.",
  'coach.stats.totalClients': 'Total Clients',
  'coach.stats.assignedToYou': 'Assigned to you',
  'coach.stats.activeMembers': 'Active Members',
  'coach.stats.activeSubscription': 'With active subscription',
  'coach.stats.onboarded': 'Onboarded',
  'coach.stats.completedQuestionnaire': 'Completed questionnaire',
  'coach.stats.pendingSetup': 'Pending Setup',
  'coach.stats.needOnboarding': 'Need onboarding',
  'coach.roster.sub': 'Your current roster',
  'coach.table.goal': 'Goal',
  'coach.backToClients': 'Back to Clients',
  'coach.actions.message': 'Message',
  'coach.actions.buildMealPlan': 'Build Meal Plan',
  'coach.actions.buildWorkoutPlan': 'Build Workout Plan',
  'coach.questionnaire.title': 'Questionnaire',
  'coach.questionnaire.sub': 'Client onboarding responses',
  'coach.questionnaire.completed': 'Completed',
  'coach.questionnaire.notCompleted': 'Questionnaire not completed yet',
  'coach.questionnaire.notCompletedSub': 'The client will fill this in on first login',
  'coach.addClient': 'Add Client',
  'coach.addClientSearch': 'Search client by email and add to your roster',
  'coach.addClientPlaceholder': 'client@example.com',
  'coach.addClientSearching': 'Searching…',
  'coach.cancelBtn': 'Cancel',
  'coach.back': 'Back',
  'coach.unnamed': 'Unnamed',
  'coach.noPlan': 'no plan',
  'coach.noSubscription': 'no subscription',
  'coach.mealPlan.newTitle': 'New Meal Plan',
  'coach.mealPlan.editTitle': 'Edit Meal Plan',
  'coach.mealPlan.planTitleLabel': 'Plan Title',
  'coach.mealPlan.description': 'Description (optional)',
  'coach.mealPlan.mealItems': 'Meal Items',
  'coach.mealPlan.addItem': '+ Add Item',
  'coach.mealPlan.sectionTitle': 'Meal Plans',
  'coach.mealPlan.sectionSub': 'Build and assign meal plans to clients',
  'coach.mealPlan.selectClient': 'Select Client',
  'coach.mealPlan.chooseClient': '— choose a client —',
  'coach.mealPlan.noPlans': 'No meal plans yet',
  'coach.mealPlan.noPlansCreate': 'Create the first plan for this client.',
  'coach.mealPlan.newPlan': 'New Plan',
  'coach.mealPlan.saving': 'Saving…',
  'coach.mealPlan.savePlan': 'Save Plan',
  'coach.mealPlan.editBtn': 'Edit',
  'coach.workout.newTitle': 'New Workout Plan',
  'coach.workout.editTitle': 'Edit Workout Plan',
  'coach.workout.sectionTitle': 'Workout Plans',
  'coach.workout.sectionSub': 'Create and manage workout programs',
  'coach.workout.noPlans': 'No workout plans yet',
  'coach.workout.noPlansCreate': 'Create the first program for this client.',
  'coach.workout.addDay': '+ Add Day',
  'coach.workout.addExercise': '+ Add Exercise',
  'coach.workout.removeDay': 'Remove day',
  'coach.workout.videoAttached': 'Video attached',
  'coach.workout.removeVideo': 'Remove',
  'coach.workout.changeVideo': 'Change',
  'coach.workout.attachVideo': 'Attach video',
  'coach.workout.selectVideo': 'Select a Video',
  'coach.workout.noVideos': 'No videos uploaded yet. Ask admin to upload workout videos.',
  'coach.workout.planTitleLabel': 'Plan Title',
  'coach.workout.description': 'Description (optional)',
  'coach.workout.newPlan': 'New Plan',
  'coach.workout.saving': 'Saving…',
  'coach.workout.savePlan': 'Save Plan',
  'coach.workout.editBtn': 'Edit',
  'coach.progress.title': 'Progress Monitor',
  'coach.progress.sub': 'View client-submitted progress and check-ins',
  'coach.progress.noData': 'No progress data yet',
  'coach.progress.noDataSub': "This client hasn't submitted any check-ins or uploads.",
  'coach.progress.bodyChecks': 'Body Check Uploads',
  'coach.progress.colDate': 'Date',
  'coach.progress.colWeight': 'Weight (kg)',
  'coach.progress.colNotes': 'Notes',
  'coach.loadingDashboard': 'Loading dashboard…',
  'coach.messages.selectClient': '— select a client —',

  // Client Dashboard — Onboarding Modal
  'client.onboarding.welcome': 'Welcome to OMR+',
  'client.onboarding.primaryGoal': "What's your primary goal?",
  'client.onboarding.bodyStats': 'Your Body Stats',
  'client.onboarding.bodyStatsSub': 'Used to calculate your personalised plan',
  'client.onboarding.activity': 'Activity & Experience',
  'client.onboarding.activitySub': 'This shapes your workout intensity',
  'client.onboarding.activityLevel': 'Activity Level',
  'client.onboarding.experience': 'Training Experience',
  'client.onboarding.health': 'Health & Dietary Info',
  'client.onboarding.healthSub': 'Helps your coach personalise your meal plan safely',
  'client.onboarding.dietaryLabel': 'Dietary Restrictions',
  'client.onboarding.dietaryPlaceholder': 'e.g. vegetarian, lactose intolerant, halal only…',
  'client.onboarding.healthLabel': 'Health Conditions',
  'client.onboarding.healthPlaceholder': 'e.g. diabetes, knee injury, hypertension…',
  'client.onboarding.privacy': 'All information is private and only visible to your assigned coach.',
  'client.onboarding.back': 'Back',
  'client.onboarding.continue': 'Continue →',
  'client.onboarding.complete': 'Complete Setup',
  'client.onboarding.gender': 'Gender',

  // Client Dashboard — Overview tab
  'client.overview.greeting.morning': 'Good morning',
  'client.overview.greeting.afternoon': 'Good afternoon',
  'client.overview.greeting.evening': 'Good evening',
  'client.overview.summary': "Here's your daily summary.",
  'client.stats.activeStreak': 'Active Streak',
  'client.stats.streakSub': 'Keep it up',
  'client.stats.mealPlan': 'Meal Plan',
  'client.stats.assigned': 'Assigned',
  'client.stats.pending': 'Pending',
  'client.stats.awaitingCoach': 'Awaiting coach',
  'client.stats.weightChange': 'Weight Change',
  'client.stats.fromFirstEntry': 'From first entry',
  'client.stats.noLogs': 'No logs yet',
  'client.stats.workoutPlan': 'Workout Plan',
  'client.quick.todaysMeals': "Today's Meals",
  'client.quick.todaysWorkout': "Today's Workout",
  'client.quick.logProgress': 'Log Progress',
  'client.quick.updateStats': 'Update your weight & stats',
  'client.quick.messageCoach': 'Message Coach',
  'client.quick.chatCoach': 'Chat with your assigned coach',
  'client.quick.noItemsToday': 'No plan assigned yet',
  'client.sub.fullCoaching': 'Full Coaching — Active',
  'client.sub.manage': 'Manage',

  // Client Dashboard — Meal Plan tab
  'client.mealPlan.sectionTitle': 'Meal Plan',
  'client.mealPlan.sectionSub': 'View your personalised meal plan assigned by your coach',
  'client.mealPlan.noItems': 'No meal plan assigned yet',
  'client.mealPlan.noItemsSub': 'Your coach will assign a meal plan once your onboarding is reviewed.',
  'client.mealPlan.assignedBy': 'Assigned by your coach · View-only',
  'client.mealPlan.requestChanges': 'Need changes to your meal plan? Message your coach directly.',
  'client.mealPlan.messageCoachBtn': 'Message Coach',

  // Client Dashboard — Workout tab
  'client.workout.sectionTitle': 'Workout Plan',
  'client.workout.sectionSub': 'Your personalised workout schedule',
  'client.workout.noItems': 'No workout plan assigned yet',
  'client.workout.noItemsSub': 'Your coach will assign a workout plan once your onboarding is reviewed.',
  'client.workout.assignedBy': 'Assigned by your coach · Tap a day to view exercises',
  'client.workout.recovery': 'Recovery day — rest, hydrate, sleep well',
  'client.workout.sets': 'Sets',
  'client.workout.reps': 'Reps',
  'client.workout.rest': 'Rest',

  // Client Dashboard — Progress tab
  'client.progress.sectionTitle': 'Progress Tracking',
  'client.progress.sectionSub': 'Log your stats, view timeline, upload body checks',
  'client.progress.logToday': "Log Today's Stats",
  'client.progress.statsSaved': 'Stats saved successfully!',
  'client.progress.weightTimeline': 'Weight Timeline',
  'client.progress.noLogs': 'No logs yet — add your first entry',
  'client.progress.totalChange': 'Total change:',
  'client.progress.logHistory': 'Log History',
  'client.progress.colDate': 'Date',
  'client.progress.colWeight': 'Weight',
  'client.progress.colChange': 'Change',
  'client.progress.colNotes': 'Notes',
  'client.progress.bodyChecks': 'Body Check Uploads',
  'client.progress.bodyChecksSub': 'Upload InBody scans, progress photos, or PDFs',
  'client.progress.uploadFile': 'Upload File',
  'client.progress.uploading': 'Uploading…',
  'client.progress.uploaded': 'Uploaded',

  // Client Dashboard — Messages tab
  'client.messages.sectionTitle': 'Messages',
  'client.messages.sectionSub': 'Direct chat with your assigned coach',
  'client.messages.noCoach': 'No coach assigned yet',
  'client.messages.noCoachSub': "You'll be able to message your coach once they're assigned by the admin.",
  'client.messages.noMessages': 'No messages yet',
  'client.messages.sendFirst': 'Send your first message to',

  // Client Dashboard — Subscription tab
  'client.sub.manageSub': 'Manage your plan, billing & invoices',
  'client.sub.activePlan': 'Active Plan',
  'client.sub.perMonth': '/month',
  'client.sub.statusLabel': 'Status',
  'client.sub.nextBilling': 'Next Billing',
  'client.sub.memberSince': 'Member Since',
  'client.sub.cancelConfirm': 'Are you sure? Your access continues until the end of the current billing period.',
  'client.sub.yesCancelSub': 'Yes, Cancel Subscription',
  'client.sub.cancelling': 'Cancelling…',
  'client.sub.keepSub': 'Keep Subscription',
  'client.sub.cancelSub': 'Cancel Subscription',
  'client.sub.invoices': 'Invoices',
  'client.sub.invoicesSub': 'Download your payment receipts',
  'client.sub.noInvoices': 'No invoices yet',
  'client.sub.viewPlansSubscribe': 'View Plans & Subscribe',
  'client.sub.noSubTitle': 'No active subscription',
  'client.sub.noSubDesc': 'Subscribe to unlock your coaching dashboard, meal plans, and direct trainer access.',
  'client.gate.title': 'Subscription Required',
  'client.gate.desc': 'Your subscription is inactive or has expired. Subscribe to unlock your full coaching dashboard — meal plans, workouts, progress tracking, and direct coach access.',
  'client.gate.viewPlans': 'View Plans',
};

// ── Arabic translations ───────────────────────────────────────────────────

const ar: Record<string, string> = {
  // Nav
  'nav.programs': 'البرامج',
  'nav.howItWorks': 'كيف يعمل',
  'nav.transformations': 'قبل وبعد',
  'nav.marketplace': 'المتجر',
  'nav.pricing': 'الأسعار',
  'nav.about': 'عن الشركة',
  'nav.contact': 'تواصل معنا',
  'nav.dashboard': 'لوحة التحكم',
  'nav.account': 'حسابي',
  'nav.soon': 'قريباً',

  // Footer
  'footer.tagline': 'تدريب رياضي متميز مع خطط غذائية مخصصة. حوّل جسمك وارتقِ بحياتك.',
  'footer.quickLinks': 'روابط سريعة',
  'footer.aboutUs': 'عن الشركة',
  'footer.ourPrograms': 'برامجنا',
  'footer.muscleBuilding': 'بناء العضلات',
  'footer.fatLoss': 'حرق الدهون',
  'footer.summerBody': 'جسم صيفي',
  'footer.workoutPlan': 'خطة التمرين',
  'footer.mealPlan': 'خطة الطعام',
  'footer.getInTouch': 'تواصل معنا',
  'footer.email': 'البريد الإلكتروني',
  'footer.whatsapp': 'واتساب',
  'footer.messageUs': 'راسلنا',
  'footer.freeConsultation': 'استشارة مجانية',
  'footer.allRightsReserved': 'جميع الحقوق محفوظة.',
  'footer.privacyPolicy': 'سياسة الخصوصية',
  'footer.termsOfService': 'شروط الخدمة',
  'footer.language': 'اللغة',
  'footer.premiumCoaching': 'تدريب متميز',
  'footer.noFreeTrials': 'لا تجارب مجانية',
  'footer.transparentPricing': 'أسعار شفافة',
  'footer.realResults': 'نتائج حقيقية',

  // Hero
  'hero.headline1': 'اكشف',
  'hero.headline2': 'إمكاناتك',
  'hero.subtext': 'انضم إلى مجتمع يُحقق الأهداف ويبني القوة ويحوّل الإمكانات إلى قوة حقيقية.',
  'hero.cta': 'ابدأ الآن',

  // Programs page
  'programs.badge': 'برامجنا',
  'programs.title': 'اختر',
  'programs.titleHighlight': 'مسارك',
  'programs.subtitle': 'كل برنامج مصمم خصيصاً لك — لجسمك وأهدافك وأسلوب حياتك. ابدأ باستشارة مجانية وسنرشدك للخطة المناسبة.',
  'programs.whatsIncluded': 'ما يشمله البرنامج',
  'programs.idealFor': 'مناسب لـ',
  'programs.startProgram': 'ابدأ هذا البرنامج',
  'programs.notSure': 'لست متأكداً من البرنامج المناسب لك؟',
  'programs.bookConsultation': 'احجز استشارة مجانية',

  // Program names
  'program.muscleBuilding.name': 'بناء العضلات',
  'program.muscleBuilding.tagline': 'بنِ عضلات متينة ودائمة',
  'program.muscleBuilding.description': 'برنامج تضخيم عضلي منظم يهدف إلى بناء العضلات عبر التحميل التدريجي والتغذية الدقيقة وتعديلات أسبوعية من المدرب. كل تكرار، كل وجبة — مصمم للنمو.',
  'program.muscleBuilding.ideal': 'مَن يرغب في زيادة الحجم، تحسين التعريف العضلي، وزيادة القوة على المدى البعيد.',
  'program.muscleBuilding.i1': 'خطة تمرين تضخيمي مخصصة (5 أيام/أسبوع)',
  'program.muscleBuilding.i2': 'نظام غذائي عالي البروتين مُكيَّف مع الماكرو',
  'program.muscleBuilding.i3': 'جلسات متابعة فردية أسبوعية مع مدربك',
  'program.muscleBuilding.i4': 'تتبع تحميل تدريجي مدمج',
  'program.muscleBuilding.i5': 'توجيهات المكملات الغذائية',

  'program.fatLoss.name': 'حرق الدهون',
  'program.fatLoss.tagline': 'احرق الدهون واحتفظ بالعضلات',
  'program.fatLoss.description': 'برنامج بعجز السعرات يحافظ على العضلات مع تقليل الدهون تدريجياً. يجمع بين الكارديو المنظم وتدريب القوة وخطة تغذية دقيقة لا تشعر معها بالحرمان.',
  'program.fatLoss.ideal': 'كل من يرغب في تقليل دهون الجسم وتحسين تركيبته الجسدية وبناء عادات صحية مستدامة.',
  'program.fatLoss.i1': 'خطة تمرين مُركَّزة على حرق الدهون',
  'program.fatLoss.i2': 'خطة غذائية بعجز سعرات مع أهداف ماكرو',
  'program.fatLoss.i3': 'متابعة أسبوعية للوزن وفحص الجسم',
  'program.fatLoss.i4': 'بروتوكول كارديو يُعدَّل أسبوعياً',
  'program.fatLoss.i5': 'تدريب على التركيز والمساءلة',

  'program.summerBody.name': 'جسم صيفي',
  'program.summerBody.tagline': '12 أسبوعاً نحو أفضل شكل',
  'program.summerBody.description': 'برنامج تحول موجَّه بموعد محدد. يجمع بين حرق الدهون ونحت العضلات للحصول على جسم رياضي ومفتول — جاهز للصيف. مصمم لنتائج حقيقية في إطار زمني واقعي.',
  'program.summerBody.ideal': 'مَن لديه إطار زمني محدد ويريد برنامج تحول كامل للجسم.',
  'program.summerBody.i1': 'خطة تمرين هجينة بين النحت وحرق الدهون',
  'program.summerBody.i2': 'نظام غذائي نظيف (بدون تجويع)',
  'program.summerBody.i3': 'تتبع تقدم تحول الجسم',
  'program.summerBody.i4': 'متابعة صور أسبوعية يراجعها المدرب',
  'program.summerBody.i5': 'نظام تحفيز ومساءلة',

  'program.workoutOnly.name': 'خطة التمرين فقط',
  'program.workoutOnly.tagline': 'تدريب منظم بدون خطة غذائية',
  'program.workoutOnly.description': 'خطة تمرين مخصصة بالكامل دون مكوّن التخطيط الغذائي. مثالية لمَن لديهم نظامهم الغذائي محدداً ويريدون هيكل تدريب احترافي.',
  'program.workoutOnly.ideal': 'مَن لديه روتين تغذية قائم ويريد هيكل تدريب احترافي.',
  'program.workoutOnly.i1': 'خطة تمرين مخصصة بالكامل',
  'program.workoutOnly.i2': 'جدول تمرين يومي',
  'program.workoutOnly.i3': 'ملاحظات المجموعات والتكرار والراحة والتقنية',
  'program.workoutOnly.i4': 'مراجع صور/فيديو للتمارين',
  'program.workoutOnly.i5': 'تحديثات شهرية للخطة',

  'program.mealOnly.name': 'خطة الطعام فقط',
  'program.mealOnly.tagline': 'تغذية دقيقة بدون تخمين',
  'program.mealOnly.description': 'خطة غذائية مخصصة بالكامل بناءً على أهدافك وقياسات جسمك وتفضيلاتك الغذائية. لا تخمين — فقط هيكل غذائي واضح ولذيذ يعمل.',
  'program.mealOnly.ideal': 'مَن يتدرب باستقلالية ويريد تغذية احترافية تُكمّل روتين التمرين الحالي.',
  'program.mealOnly.i1': 'خطة وجبات مخصصة (إفطار، غداء، سناك، عشاء)',
  'program.mealOnly.i2': 'أهداف الماكرو والسعرات لكل وجبة',
  'program.mealOnly.i3': 'احترام كامل للقيود الغذائية',
  'program.mealOnly.i4': 'خيارات غذائية مناسبة للبقالة',
  'program.mealOnly.i5': 'تجديد شهري لخطة الوجبات',

  // About page
  'about.badge': 'عن OMR+',
  'about.title': 'تدريب متميز،',
  'about.titleHighlight': 'نتائج حقيقية',
  'about.subtitle': 'OMR+ منصة تدريب رياضي متميزة مبنية لمن هم جادون في تحويل أجسامهم — بتوجيه احترافي، لا بالتخمين.',
  'about.mission.title': 'مهمتنا',
  'about.mission.body': 'تقديم تدريب رياضي عالمي المستوى يكون متاحاً ومخصصاً ومبنياً على نتائج حقيقية — لا وعود فارغة.',
  'about.approach.title': 'نهجنا',
  'about.approach.body': 'كل عميل يحصل على خطة مخصصة بالكامل — تمارين مصممة خصيصاً، خطط غذائية مخصصة، ومتابعة أسبوعية مع مدرب مخصص.',
  'about.values.title': 'قيمنا',
  'about.values.b1': 'التخصيص بدلاً من الخطط العامة',
  'about.values.b2': 'الشفافية والتواصل الصادق',
  'about.values.b3': 'المساءلة الموجهة بالنتائج',
  'about.values.b4': 'الجودة المتميزة في كل ما نقدمه',
  'about.cta': 'ابدأ تحولك',

  // Contact page
  'contact.badge': 'تواصل معنا',
  'contact.title': 'لنتحدث',
  'contact.titleHighlight': '',
  'contact.subtitle': 'هل لديك سؤال أو أنت مستعد للبدء؟ تواصل معنا وسنرد عليك.',
  'contact.whatsapp.title': 'واتساب',
  'contact.whatsapp.desc': 'راسلنا مباشرة للحصول على أسرع رد.',
  'contact.whatsapp.btn': 'المراسلة على واتساب',
  'contact.email.title': 'البريد الإلكتروني',
  'contact.email.desc': 'أرسل لنا رسالة وسنرد في غضون 24 ساعة.',
  'contact.form.title': 'أرسل رسالة',
  'contact.form.name': 'الاسم الكامل',
  'contact.form.namePlaceholder': 'اسمك',
  'contact.form.email': 'البريد الإلكتروني',
  'contact.form.emailPlaceholder': 'بريدك@مثال.com',
  'contact.form.message': 'الرسالة',
  'contact.form.messagePlaceholder': 'كيف يمكننا مساعدتك؟',
  'contact.form.submit': 'إرسال الرسالة',
  'contact.form.sending': 'جارٍ الإرسال…',
  'contact.form.success': 'تم إرسال الرسالة! سنتواصل معك قريباً.',

  // Marketplace page
  'marketplace.badge': 'المتجر',
  'marketplace.title': 'مكملات متميزة',
  'marketplace.titleHighlight': 'والمزيد',
  'marketplace.subtitle': 'مكملات ومنتجات تغذية ومصادر متخصصة لدعم رحلتك الرياضية.',
  'marketplace.comingSoon': 'قريباً',
  'marketplace.comingSoonTitle': 'المتجر يفتح قريباً',
  'marketplace.comingSoonDesc': 'نقوم باختيار أفضل المكملات ومنتجات التغذية لك. تابعنا قريباً.',
  'marketplace.notifyBtn': 'أعلمني',

  // How It Works section
  'hiw.badge': 'كيف يعمل',
  'hiw.title': 'رحلتك نحو',
  'hiw.titleHighlight': 'التحول',
  'hiw.step1.title': 'استشارة مجانية',
  'hiw.step1.desc': 'احجز استشارة مجانية مع فريقنا. سنقيّم أهدافك وأسلوب حياتك ومستواك الرياضي لمطابقتك مع البرنامج المناسب.',
  'hiw.step2.title': 'احصل على خطتك',
  'hiw.step2.desc': 'احصل على خطة تمرين وتغذية مخصصة بالكامل، مُصممة خصيصاً لجسمك وأهدافك وجدولك.',
  'hiw.step3.title': 'دعم المدرب',
  'hiw.step3.desc': 'ابق على تواصل مع مدربك المخصص. متابعة أسبوعية وتعديلات على الخطة ومراسلة فورية لإبقائك على المسار.',
  'hiw.step4.title': 'تتبع التقدم',
  'hiw.step4.desc': 'سجّل تقدمك، ارفع فحوصات الجسم، وشاهد تحولك يتكشف بأفكار مبنية على البيانات.',

  // Transformations section
  'trans.badge': 'قبل وبعد',
  'trans.title': 'أشخاص حقيقيون،',
  'trans.titleHighlight': 'نتائج حقيقية',
  'trans.subtitle': 'تحولات عملاء محمية بالخصوصية. النتائج تتفاوت حسب التزام الفرد والبرنامج.',
  'trans.disclaimer': 'هويات العملاء محمية. النتائج المعروضة بإذن.',
  'trans.verified': 'نتيجة موثقة',
  'trans.more': 'مئات القصص الأخرى تنتظر أن تُروى',
  'trans.viewAll': 'عرض جميع التحولات',
  'trans.t1.label': 'خسر',
  'trans.t1.program': 'فقدان الدهون',
  'trans.t1.duration': '١٢ أسبوعاً',
  'trans.t1.change': 'تحسّن تكوين الجسم بشكل ملحوظ. التدريب المنتظم والتغذية المخصصة صنعا الفارق.',
  'trans.t2.label': 'اكتسب',
  'trans.t2.program': 'بناء العضلات',
  'trans.t2.duration': '١٦ أسبوعاً',
  'trans.t2.change': 'زادت القوة بنسبة ٤٠٪. التحميل التدريجي وتخطيط التغذية الدقيق أرسيا أساساً يدوم.',
  'trans.t3.label': 'ثقة',
  'trans.t3.program': 'جسم صيفي',
  'trans.t3.duration': '١٢ أسبوعاً',
  'trans.t3.change': 'طاقة أكبر، قوام أفضل، وجسم يستحق الفخر — تحقّق بفضل الاتساق والإرشاد المتخصص.',
  'trans.stat1': 'عضو نشط',
  'trans.stat2': 'نسبة النجاح',
  'trans.stat3': 'متوسط المدة',
  'trans.stat4': 'متابعة منجزة',

  // Pricing section
  'pricing.badge': 'الأسعار',
  'pricing.title': 'أسعار',
  'pricing.titleHighlight': 'شفافة وبسيطة',
  'pricing.subtitle': 'لا رسوم خفية. لا تجارب مجانية. اختر الخطة التي تناسب أهدافك.',
  'pricing.perMonth': '/شهر',
  'pricing.getStarted': 'ابدأ الآن',
  'pricing.popular': 'الأكثر شعبية',
  'pricing.consultation': 'احجز استشارة مجانية',
  'pricing.footer1': 'جميع الأسعار بالريال السعودي. تُدار الأسعار من لوحة التحكم وقد تتغير.',
  'pricing.footer2': 'لست متأكداً من الخطة المناسبة؟ احجز استشارتك المجانية — بدون أي التزام.',
  'pricing.plan1.name': 'الخطة فقط',
  'pricing.plan1.tagline': 'تدرّب بوتيرتك الخاصة',
  'pricing.plan1.desc': 'احصل على خطة غذاء أو تمرين مخصصة بالكامل حول جسمك وأهدافك وأسلوب حياتك.',
  'pricing.plan1.cta': 'ابدأ الآن',
  'pricing.plan1.f1': 'خطة غذاء أو تمرين مخصصة',
  'pricing.plan1.f2': 'مصممة وفق أهدافك',
  'pricing.plan1.f3': 'مراعاة القيود الغذائية',
  'pricing.plan1.f4': 'تحديث أسبوعي للخطة',
  'pricing.plan1.f5': 'إمكانية تحميل PDF',
  'pricing.plan2.name': 'التدريب الكامل',
  'pricing.plan2.tagline': 'البرنامج الأكثر اختياراً',
  'pricing.plan2.desc': 'تجربة تدريب متكاملة — خطط مخصصة، متابعة أسبوعية، ووصول مباشر لمدربك.',
  'pricing.plan2.cta': 'ابدأ التدريب',
  'pricing.plan2.f1': 'خطة غذاء + تمرين مخصصة',
  'pricing.plan2.f2': 'مدرب شخصي مخصص',
  'pricing.plan2.f3': 'متابعة أسبوعية فردية',
  'pricing.plan2.f4': 'مراسلة فورية مع المدرب',
  'pricing.plan2.f5': 'تتبع التقدم وتعديل الخطط',
  'pricing.plan2.f6': 'دعم تحليل InBody',
  'pricing.plan2.f7': 'تحديثات ذات أولوية للخطة',
  'pricing.plan3.name': 'النخبة',
  'pricing.plan3.tagline': 'أقصى النتائج',
  'pricing.plan3.desc': 'تجربة OMR+ الكاملة — تدريب نخبوي مع إضافات متميزة لمن يريد الأفضل.',
  'pricing.plan3.cta': 'انضم للنخبة',
  'pricing.plan3.f1': 'كل مزايا التدريب الكامل',
  'pricing.plan3.f2': 'رسائل غير محدودة مع المدرب',
  'pricing.plan3.f3': 'استشارات فيديو كل أسبوعين',
  'pricing.plan3.f4': 'إرشاد المكملات الغذائية',
  'pricing.plan3.f5': 'دعم التحضير للمسابقات',
  'pricing.plan3.f6': 'تأهيل ذو أولوية',

  // Consultation CTA
  'cta.title': 'مستعد للتحول؟',
  'cta.subtitle': 'احجز استشارتك المجانية اليوم واخطُ أولى خطواتك نحو الجسم الذي تستحقه.',
  'cta.btn': 'احجز استشارة مجانية',

  // Testimonials
  'testimonials.badge': 'آراء العملاء',
  'testimonials.title': 'ما يقوله',
  'testimonials.titleHighlight': 'أعضاؤنا',

  // Login page
  'login.memberPortal': 'بوابة الأعضاء',
  'login.title': 'مرحباً بعودتك',
  'login.subtitle': 'سجّل دخولك للوصول إلى لوحة التدريب',
  'login.email': 'البريد الإلكتروني',
  'login.emailPlaceholder': 'أنت@مثال.com',
  'login.password': 'كلمة المرور',
  'login.forgotPassword': 'نسيت كلمة المرور؟',
  'login.signIn': 'تسجيل الدخول',
  'login.signingIn': 'جارٍ تسجيل الدخول…',
  'login.noAccount': 'ليس لديك حساب؟',
  'login.createOne': 'أنشئ حساباً',
  'login.secureLogin': 'تسجيل آمن',
  'login.dataPrivate': 'بياناتك خاصة',

  // Signup page
  'signup.memberPortal': 'عضو جديد',
  'signup.title': 'أنشئ حسابك',
  'signup.subtitle': 'انضم إلى OMR+ وابدأ تحولك',
  'signup.fullName': 'الاسم الكامل',
  'signup.fullNamePlaceholder': 'اسمك الكامل',
  'signup.email': 'البريد الإلكتروني',
  'signup.emailPlaceholder': 'أنت@مثال.com',
  'signup.password': 'كلمة المرور',
  'signup.passwordPlaceholder': '••••••••',
  'signup.confirmPassword': 'تأكيد كلمة المرور',
  'signup.confirmPlaceholder': '••••••••',
  'signup.createAccount': 'إنشاء حساب',
  'signup.creating': 'جارٍ الإنشاء…',
  'signup.haveAccount': 'لديك حساب بالفعل؟',
  'signup.signIn': 'سجّل دخولك',
  'signup.secureSignup': 'تسجيل آمن',
  'signup.dataPrivate': 'بياناتك خاصة',

  // Dashboard Shell
  'dash.memberPortal': 'بوابة الأعضاء',
  'dash.coachPortal': 'بوابة المدرب',
  'dash.adminPanel': 'لوحة الإدارة',
  'dash.signOut': 'تسجيل الخروج',
  'dash.backToSite': 'العودة للموقع',

  // Client Dashboard
  'client.overview': 'نظرة عامة',
  'client.mealPlan': 'خطة الطعام',
  'client.workoutPlan': 'خطة التمرين',
  'client.progress': 'التقدم',
  'client.messages': 'الرسائل',
  'client.subscription': 'الاشتراك',
  'client.welcome': 'مرحباً بعودتك',
  'client.yourCoach': 'مدربك',
  'client.noCoach': 'لم يتم تعيين مدرب بعد',
  'client.activePlan': 'الخطة النشطة',
  'client.loading': 'جارٍ التحميل…',
  'client.noMealPlan': 'لم يتم تعيين خطة طعام بعد',
  'client.noWorkoutPlan': 'لم يتم تعيين خطة تمرين بعد',
  'client.watchVideo': 'مشاهدة',

  // Coach Dashboard
  'coach.clients': 'العملاء',
  'coach.mealBuilder': 'بناء الوجبات',
  'coach.workoutBuilder': 'بناء التمارين',
  'coach.progress': 'التقدم',
  'coach.messages': 'الرسائل',
  'coach.welcome': 'مرحباً بك، أيها المدرب',
  'coach.myClients': 'عملائي',
  'coach.assignedClients': 'العملاء المُعيَّنون',

  // Admin Dashboard
  'admin.overview': 'نظرة عامة',
  'admin.users': 'المستخدمون',
  'admin.coaches': 'المدربون',
  'admin.subscriptions': 'الاشتراكات',
  'admin.marketplace': 'المتجر',
  'admin.pricing': 'الأسعار',
  'admin.videos': 'الفيديوهات',
  'admin.analytics': 'التحليلات',
  'admin.chat': 'المحادثات',
  'admin.welcome': 'مرحباً، المدير',

  // Admin Dashboard — extended labels
  'admin.platformOverview': 'نظرة عامة على المنصة',
  'admin.platformSubtitle': 'تحكم كامل في منصة OMR+.',
  'admin.totalMembers': 'إجمالي الأعضاء',
  'admin.registeredClients': 'عملاء مسجلون',
  'admin.activeCoaches': 'المدربون النشطون',
  'admin.platformTrainers': 'مدربو المنصة',
  'admin.activeSubscriptions': 'الاشتراكات النشطة',
  'admin.payingMembers': 'أعضاء يدفعون',
  'admin.monthlyRevenue': 'الإيراد الشهري',
  'admin.activeSubscriptionsLabel': 'الاشتراكات النشطة',
  'admin.recentMembers': 'الأعضاء الأخيرون',
  'admin.viewAll': 'عرض الكل',
  'admin.manage': 'إدارة',
  'admin.noMembers': 'لا أعضاء بعد',
  'admin.noCoaches': 'لا مدربون بعد',
  'admin.clients': 'عملاء',
  'admin.statusActive': 'نشط',
  'admin.statusFree': 'مجاني',
  'admin.member': 'العضو',
  'admin.status': 'الحالة',
  'admin.onboarded': 'مُوَجَّه',
  'admin.coach': 'المدرب',
  'admin.joined': 'انضم',
  'admin.unnamed': 'بدون اسم',
  'admin.yes': 'نعم',
  'admin.no': 'لا',
  'admin.noCoachAssigned': '—',
  'admin.saving': 'جارٍ الحفظ…',
  'admin.save': 'حفظ',
  'admin.cancel': 'إلغاء',
  'admin.addPlan': '+ إضافة خطة',
  'admin.editPlan': 'تعديل الخطة',
  'admin.newPlan': 'خطة جديدة',
  'admin.delete': 'حذف',
  'admin.publish': 'نشر',
  'admin.unpublish': 'إلغاء النشر',
  'admin.createCoach': 'إنشاء حساب مدرب',
  'admin.assignCoach': 'تعيين مدرب',
  'admin.usersTab': 'المستخدمون',
  'admin.loading': 'جارٍ التحميل…',
  'admin.noData': 'لا توجد بيانات',

  // Client Dashboard — extended labels
  'client.overviewTitle': 'نظرة عامة',
  'client.welcomeBack': 'مرحباً بعودتك',
  'client.subscriptionActive': 'نشط',
  'client.subscriptionExpired': 'منتهي',
  'client.noSubscription': 'لا يوجد اشتراك نشط',
  'client.upgradeNow': 'ترقية الآن',
  'client.logWeight': 'تسجيل الوزن',
  'client.weightKg': 'الوزن (كجم)',
  'client.notes': 'ملاحظات (اختياري)',
  'client.saveEntry': 'حفظ السجل',
  'client.saving': 'جارٍ الحفظ…',
  'client.progressHistory': 'سجل التقدم',
  'client.noProgress': 'لم يتم تسجيل تقدم بعد',
  'client.sendMessage': 'إرسال',
  'client.messagePlaceholder': 'اكتب رسالة…',
  'client.noMessages': 'لا رسائل بعد',
  'client.online': 'متصل',

  // Coach Dashboard — extended labels
  'coach.overview': 'نظرة عامة',
  'coach.loading': 'جارٍ التحميل…',
  'coach.noClients': 'لم يتم تعيين عملاء بعد',
  'coach.selectClient': 'اختر عميلاً للبدء في المحادثة',
  'coach.messagePlaceholder': 'اكتب رسالة…',
  'coach.send': 'إرسال',
  'coach.noMessages': 'لا رسائل بعد. قل مرحباً!',
  'coach.onboarded': 'مُوَجَّه',
  'coach.notOnboarded': 'لم يُوَجَّه بعد',
  'coach.active': 'نشط',

  // Home Programs Section
  'home.programs.badge': 'برامجنا',
  'home.programs.title': 'اختر',
  'home.programs.titleHighlight': 'مسارك',
  'home.programs.subtitle': 'اختر البرنامج الذي يناسب أهدافك. جميع الخطط تشمل دعماً مخصصاً.',
  'home.programs.getStarted': 'ابدأ الآن',
  'home.programs.viewAll': 'عرض جميع البرامج',
  'home.programs.viewAllSub': 'تريد الاطلاع على جميع البرامج بالتفصيل؟',
  'home.programs.muscleBuilding': 'بناء العضلات',
  'home.programs.muscleBuilding.desc': 'بناء كتلة عضلية بتدريب قوة تدريجي وخطط غذائية غنية بالبروتين.',
  'home.programs.fatLoss': 'حرق الدهون',
  'home.programs.fatLoss.desc': 'حرق دهون مستدام من خلال تغذية منظمة وتمارين كارديو وقوة.',
  'home.programs.summerBody': 'جسم صيفي',
  'home.programs.summerBody.desc': 'تحوّل في 12 أسبوع مع برنامجنا المدعوم علمياً.',
  'home.programs.workoutPlan': 'خطة التمرين',
  'home.programs.workoutPlan.desc': 'خطط تمرين منظمة بدون تخطيط غذائي. مثالية لمن لديه نظامه الغذائي.',
  'home.programs.mealPlan': 'خطة الطعام',
  'home.programs.mealPlan.desc': 'احصل على خطط غذائية مخصصة تناسب أهدافك وتفضيلاتك الغذائية.',

  // Testimonials Section — extended
  'testimonials.subtitle': 'آراء حقيقية من أعضاء التزموا بالعملية وخرجوا متحولين.',
  'testimonials.m1.quote': 'OMR+ غيّر مسيرتي تماماً. الخطط الغذائية المخصصة ودعم المدرب جعل كل أسبوع منظماً وقابلاً للتحقيق. فقدت 20 كيلو واكتسبت علاقة مختلفة تماماً مع جسدي.',
  'testimonials.m1.role': 'برنامج حرق الدهون',
  'testimonials.m2.quote': 'الاحترافية هنا لا مثيل لها. عدّل مدربي برنامجي كل أسبوع بناءً على بيانات حقيقية. لم أشعر أنه خطة عامة — بل شعرت أنها مبنية خصيصاً لي.',
  'testimonials.m2.role': 'برنامج بناء العضلات',
  'testimonials.m3.quote': 'كنت متشككاً في البداية، لكن خلال ستة أسابيع كانت النتائج لا يمكن إنكارها. التدريب والمساءلة ودقة خطة التغذية — لا شيء يقارن.',
  'testimonials.m3.role': 'برنامج الجسم الصيفي',
  'testimonials.m4.quote': 'يستحق كل ريال. عندما أردت الاستسلام في الأسبوع الرابع، كان مدربي موجوداً بالتعديل الصحيح والكلمات الصحيحة. أفضل استثمار قمت به في نفسي.',
  'testimonials.m4.role': 'التدريب النخبوي',

  // Admin — Subscriptions tab
  'admin.subscriptionsTitle': 'الاشتراكات',
  'admin.totalSubscriptions': 'اشتراك إجمالي',
  'admin.filterAll': 'الكل',
  'admin.filterActive': 'نشط',
  'admin.filterCancelled': 'ملغي',
  'admin.filterExpired': 'منتهي',
  'admin.colPlan': 'الخطة',
  'admin.colAmount': 'المبلغ',
  'admin.colStart': 'البداية',
  'admin.colExpires': 'الانتهاء',
  'admin.noSubscriptions': 'لا توجد اشتراكات',

  // Admin — Marketplace tab
  'admin.marketplaceTitle': 'المتجر',
  'admin.marketplaceSub': 'إدارة المنتجات والكتب الإلكترونية',
  'admin.addProduct': '+ إضافة منتج',
  'admin.activeInStore': 'نشط (مرئي في المتجر)',

  // Admin — Pricing tab
  'admin.pricingTitle': 'خطط الأسعار',
  'admin.pricingSubtitle': 'أنشئ خططاً مع معرّفات أسعار Stripe — انشر لعرضها على الموقع.',

  // Admin — Chat tab
  'admin.chatTitle': 'محادثات الدردشة',
  'admin.chatSubtitle': 'جميع محادثات العملاء والمدربين',
  'admin.colClient': 'العميل',
  'admin.colCoach': 'المدرب',
  'admin.colStarted': 'البداية',
  'admin.viewThread': 'عرض',
  'admin.noConversations': 'لا محادثات بعد',
  'admin.noConversationsSub': 'تظهر محادثات الدردشة هنا بمجرد أن يبدأ العملاء والمدربون في التراسل.',

  // Admin — Videos tab
  'admin.videosTitle': 'فيديوهات التمرين',
  'admin.uploadVideo': 'رفع فيديو',
  'admin.uploading': 'جارٍ الرفع',
  'admin.processing': 'جارٍ المعالجة…',
  'admin.uploadingVideo': 'جارٍ رفع الفيديو…',
  'admin.processingCloudinary': 'جارٍ المعالجة على Cloudinary…',

  // Admin — Analytics tab
  'admin.analyticsTitle': 'التحليلات',
  'admin.analyticsSub': 'ملخص أداء المنصة',
  'admin.totalRegistered': 'إجمالي المسجلين',
  'admin.allTimeSignups': 'إجمالي التسجيلات',
  'admin.activeSubscribers': 'المشتركون النشطون',
  'admin.currentlyPaying': 'يدفعون حالياً',
  'admin.churned': 'الملغون',
  'admin.cancelledSubscriptions': 'اشتراكات ملغاة',
  'admin.onboardingRate': 'معدل التأهيل',
  'admin.completedQuestionnaire': 'أكمل الاستبيان',
  'admin.fromActivePlans': 'من الخطط النشطة',
  'admin.avgRevenueUser': 'متوسط الإيراد/مستخدم',
  'admin.perRegisteredClient': 'لكل عميل مسجل',
  'admin.newMembers': 'الأعضاء الجدد',
  'admin.last6Months': 'آخر 6 أشهر',
  'admin.revenueSAR': 'الإيراد (ريال)',
  'admin.subscriptionBreakdown': 'توزيع الاشتراكات',
  'admin.statusDistribution': 'توزيع الحالات',
  'admin.statusCancelled': 'ملغي',
  'admin.statusExpired': 'منتهي',
  'admin.statusPastDue': 'متأخر',

  // Coach Dashboard — additional UI strings
  'coach.overview.summary': 'إليك ملخص نشاطك في التدريب.',
  'coach.stats.totalClients': 'إجمالي العملاء',
  'coach.stats.assignedToYou': 'مخصص لك',
  'coach.stats.activeMembers': 'الأعضاء النشطون',
  'coach.stats.activeSubscription': 'باشتراك نشط',
  'coach.stats.onboarded': 'مكتمل الإعداد',
  'coach.stats.completedQuestionnaire': 'أكمل الاستبيان',
  'coach.stats.pendingSetup': 'في انتظار الإعداد',
  'coach.stats.needOnboarding': 'يحتاج إلى إعداد',
  'coach.roster.sub': 'قائمة عملائك الحالية',
  'coach.table.goal': 'الهدف',
  'coach.backToClients': 'رجوع إلى العملاء',
  'coach.actions.message': 'مراسلة',
  'coach.actions.buildMealPlan': 'بناء خطة الوجبات',
  'coach.actions.buildWorkoutPlan': 'بناء خطة التمرين',
  'coach.questionnaire.title': 'الاستبيان',
  'coach.questionnaire.sub': 'إجابات العميل على استبيان الإعداد',
  'coach.questionnaire.completed': 'مكتمل',
  'coach.questionnaire.notCompleted': 'لم يكتمل الاستبيان بعد',
  'coach.questionnaire.notCompletedSub': 'سيملأ العميل هذا عند تسجيل الدخول لأول مرة',
  'coach.addClient': 'إضافة عميل',
  'coach.addClientSearch': 'ابحث عن عميل بالبريد الإلكتروني وأضفه إلى قائمتك',
  'coach.addClientPlaceholder': 'عميل@مثال.com',
  'coach.addClientSearching': 'جارٍ البحث…',
  'coach.cancelBtn': 'إلغاء',
  'coach.back': 'رجوع',
  'coach.unnamed': 'بدون اسم',
  'coach.noPlan': 'لا توجد خطة',
  'coach.noSubscription': 'لا يوجد اشتراك',
  'coach.mealPlan.newTitle': 'خطة وجبات جديدة',
  'coach.mealPlan.editTitle': 'تعديل خطة الوجبات',
  'coach.mealPlan.planTitleLabel': 'عنوان الخطة',
  'coach.mealPlan.description': 'الوصف (اختياري)',
  'coach.mealPlan.mealItems': 'عناصر الوجبات',
  'coach.mealPlan.addItem': '+ إضافة عنصر',
  'coach.mealPlan.sectionTitle': 'خطط الوجبات',
  'coach.mealPlan.sectionSub': 'بناء وتعيين خطط الوجبات للعملاء',
  'coach.mealPlan.selectClient': 'اختر عميلاً',
  'coach.mealPlan.chooseClient': '— اختر عميلاً —',
  'coach.mealPlan.noPlans': 'لا توجد خطط وجبات بعد',
  'coach.mealPlan.noPlansCreate': 'أنشئ أول خطة لهذا العميل.',
  'coach.mealPlan.newPlan': 'خطة جديدة',
  'coach.mealPlan.saving': 'جارٍ الحفظ…',
  'coach.mealPlan.savePlan': 'حفظ الخطة',
  'coach.mealPlan.editBtn': 'تعديل',
  'coach.workout.newTitle': 'خطة تمرين جديدة',
  'coach.workout.editTitle': 'تعديل خطة التمرين',
  'coach.workout.sectionTitle': 'خطط التمرين',
  'coach.workout.sectionSub': 'إنشاء وإدارة برامج التمرين',
  'coach.workout.noPlans': 'لا توجد خطط تمرين بعد',
  'coach.workout.noPlansCreate': 'أنشئ أول برنامج لهذا العميل.',
  'coach.workout.addDay': '+ إضافة يوم',
  'coach.workout.addExercise': '+ إضافة تمرين',
  'coach.workout.removeDay': 'حذف اليوم',
  'coach.workout.videoAttached': 'فيديو مرفق',
  'coach.workout.removeVideo': 'إزالة',
  'coach.workout.changeVideo': 'تغيير',
  'coach.workout.attachVideo': 'إرفاق فيديو',
  'coach.workout.selectVideo': 'اختر فيديو',
  'coach.workout.noVideos': 'لا توجد فيديوهات بعد. اطلب من المدير رفع فيديوهات التمرين.',
  'coach.workout.planTitleLabel': 'عنوان الخطة',
  'coach.workout.description': 'الوصف (اختياري)',
  'coach.workout.newPlan': 'خطة جديدة',
  'coach.workout.saving': 'جارٍ الحفظ…',
  'coach.workout.savePlan': 'حفظ الخطة',
  'coach.workout.editBtn': 'تعديل',
  'coach.progress.title': 'مراقبة التقدم',
  'coach.progress.sub': 'عرض التقدم والفحوصات التي يرسلها العملاء',
  'coach.progress.noData': 'لا توجد بيانات تقدم بعد',
  'coach.progress.noDataSub': 'لم يقدّم هذا العميل أي فحوصات أو رفع ملفات بعد.',
  'coach.progress.bodyChecks': 'رفع فحوصات الجسم',
  'coach.progress.colDate': 'التاريخ',
  'coach.progress.colWeight': 'الوزن (كجم)',
  'coach.progress.colNotes': 'ملاحظات',
  'coach.loadingDashboard': 'جارٍ تحميل لوحة التحكم…',
  'coach.messages.selectClient': '— اختر عميلاً —',

  // Client Dashboard — Onboarding Modal
  'client.onboarding.welcome': 'مرحباً بك في OMR+',
  'client.onboarding.primaryGoal': 'ما هو هدفك الرئيسي؟',
  'client.onboarding.bodyStats': 'إحصائيات جسمك',
  'client.onboarding.bodyStatsSub': 'تُستخدم لحساب خطتك الشخصية',
  'client.onboarding.activity': 'النشاط والخبرة',
  'client.onboarding.activitySub': 'يحدد هذا شدة تمرينك',
  'client.onboarding.activityLevel': 'مستوى النشاط',
  'client.onboarding.experience': 'خبرة التدريب',
  'client.onboarding.health': 'المعلومات الصحية والغذائية',
  'client.onboarding.healthSub': 'يساعد مدربك على تخصيص خطة وجباتك بأمان',
  'client.onboarding.dietaryLabel': 'القيود الغذائية',
  'client.onboarding.dietaryPlaceholder': 'مثال: نباتي، عدم تحمل اللاكتوز، حلال فقط…',
  'client.onboarding.healthLabel': 'الحالات الصحية',
  'client.onboarding.healthPlaceholder': 'مثال: سكري، إصابة في الركبة، ضغط دم…',
  'client.onboarding.privacy': 'جميع المعلومات خاصة ولا يراها إلا مدربك المعيَّن.',
  'client.onboarding.back': 'رجوع',
  'client.onboarding.continue': 'متابعة →',
  'client.onboarding.complete': 'إتمام الإعداد',
  'client.onboarding.gender': 'الجنس',

  // Client Dashboard — Overview tab
  'client.overview.greeting.morning': 'صباح الخير',
  'client.overview.greeting.afternoon': 'مساء الخير',
  'client.overview.greeting.evening': 'مساء النور',
  'client.overview.summary': 'إليك ملخصك اليومي.',
  'client.stats.activeStreak': 'تواصل النشاط',
  'client.stats.streakSub': 'واصل الجهد',
  'client.stats.mealPlan': 'خطة الوجبات',
  'client.stats.assigned': 'مُعيَّنة',
  'client.stats.pending': 'في الانتظار',
  'client.stats.awaitingCoach': 'في انتظار المدرب',
  'client.stats.weightChange': 'تغيير الوزن',
  'client.stats.fromFirstEntry': 'من أول تسجيل',
  'client.stats.noLogs': 'لا سجلات بعد',
  'client.stats.workoutPlan': 'خطة التمرين',
  'client.quick.todaysMeals': 'وجبات اليوم',
  'client.quick.todaysWorkout': 'تمرين اليوم',
  'client.quick.logProgress': 'تسجيل التقدم',
  'client.quick.updateStats': 'حدّث وزنك وإحصائياتك',
  'client.quick.messageCoach': 'مراسلة المدرب',
  'client.quick.chatCoach': 'تواصل مع مدربك المعيَّن',
  'client.quick.noItemsToday': 'لم يتم تعيين خطة بعد',
  'client.sub.fullCoaching': 'التدريب الكامل — نشط',
  'client.sub.manage': 'إدارة',

  // Client Dashboard — Meal Plan tab
  'client.mealPlan.sectionTitle': 'خطة الوجبات',
  'client.mealPlan.sectionSub': 'اعرض خطة وجباتك الشخصية التي عيَّنها مدربك',
  'client.mealPlan.noItems': 'لم يتم تعيين خطة وجبات بعد',
  'client.mealPlan.noItemsSub': 'سيعيّن مدربك خطة وجبات بعد مراجعة إعدادك.',
  'client.mealPlan.assignedBy': 'مُعيَّنة من مدربك · للعرض فقط',
  'client.mealPlan.requestChanges': 'هل تحتاج إلى تغييرات في خطة وجباتك؟ راسل مدربك مباشرة.',
  'client.mealPlan.messageCoachBtn': 'مراسلة المدرب',

  // Client Dashboard — Workout tab
  'client.workout.sectionTitle': 'خطة التمرين',
  'client.workout.sectionSub': 'جدول تمرينك الشخصي',
  'client.workout.noItems': 'لم يتم تعيين خطة تمرين بعد',
  'client.workout.noItemsSub': 'سيعيّن مدربك خطة تمرين بعد مراجعة إعدادك.',
  'client.workout.assignedBy': 'مُعيَّنة من مدربك · اضغط على يوم لعرض التمارين',
  'client.workout.recovery': 'يوم تعافٍ — استرح، اشرب الماء، نم جيداً',
  'client.workout.sets': 'مجموعات',
  'client.workout.reps': 'تكرارات',
  'client.workout.rest': 'راحة',

  // Client Dashboard — Progress tab
  'client.progress.sectionTitle': 'تتبع التقدم',
  'client.progress.sectionSub': 'سجّل إحصائياتك، اعرض الجدول الزمني، ارفع فحوصات الجسم',
  'client.progress.logToday': 'سجّل إحصائيات اليوم',
  'client.progress.statsSaved': 'تم حفظ الإحصائيات بنجاح!',
  'client.progress.weightTimeline': 'الجدول الزمني للوزن',
  'client.progress.noLogs': 'لا سجلات بعد — أضف أول إدخال',
  'client.progress.totalChange': 'التغيير الإجمالي:',
  'client.progress.logHistory': 'سجل التاريخ',
  'client.progress.colDate': 'التاريخ',
  'client.progress.colWeight': 'الوزن',
  'client.progress.colChange': 'التغيير',
  'client.progress.colNotes': 'ملاحظات',
  'client.progress.bodyChecks': 'رفع فحوصات الجسم',
  'client.progress.bodyChecksSub': 'ارفع فحوصات InBody أو صور التقدم أو ملفات PDF',
  'client.progress.uploadFile': 'رفع ملف',
  'client.progress.uploading': 'جارٍ الرفع…',
  'client.progress.uploaded': 'تم الرفع',

  // Client Dashboard — Messages tab
  'client.messages.sectionTitle': 'الرسائل',
  'client.messages.sectionSub': 'دردشة مباشرة مع مدربك المعيَّن',
  'client.messages.noCoach': 'لم يتم تعيين مدرب بعد',
  'client.messages.noCoachSub': 'ستتمكن من مراسلة مدربك بمجرد تعيينه من قِبل المدير.',
  'client.messages.noMessages': 'لا رسائل بعد',
  'client.messages.sendFirst': 'أرسل أول رسالة إلى',

  // Client Dashboard — Subscription tab
  'client.sub.manageSub': 'إدارة خطتك والفواتير',
  'client.sub.activePlan': 'الخطة النشطة',
  'client.sub.perMonth': '/شهر',
  'client.sub.statusLabel': 'الحالة',
  'client.sub.nextBilling': 'الفاتورة القادمة',
  'client.sub.memberSince': 'عضو منذ',
  'client.sub.cancelConfirm': 'هل أنت متأكد؟ يستمر وصولك حتى نهاية فترة الفوترة الحالية.',
  'client.sub.yesCancelSub': 'نعم، إلغاء الاشتراك',
  'client.sub.cancelling': 'جارٍ الإلغاء…',
  'client.sub.keepSub': 'الإبقاء على الاشتراك',
  'client.sub.cancelSub': 'إلغاء الاشتراك',
  'client.sub.invoices': 'الفواتير',
  'client.sub.invoicesSub': 'تحميل إيصالات الدفع',
  'client.sub.noInvoices': 'لا فواتير بعد',
  'client.sub.viewPlansSubscribe': 'عرض الخطط والاشتراك',
  'client.sub.noSubTitle': 'لا يوجد اشتراك نشط',
  'client.sub.noSubDesc': 'اشترك لفتح لوحة التدريب وخطط الوجبات والتواصل المباشر مع مدربك.',
  'client.gate.title': 'الاشتراك مطلوب',
  'client.gate.desc': 'اشتراكك غير نشط أو انتهت صلاحيته. اشترك لفتح لوحة التدريب الكاملة — خطط الوجبات والتمارين وتتبع التقدم والتواصل المباشر مع المدرب.',
  'client.gate.viewPlans': 'عرض الخطط',
};

// ── Provider ─────────────────────────────────────────────────────────────────

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('omr_lang') as Language | null;
    if (saved === 'ar' || saved === 'en') setLangState(saved);
  }, []);

  const setLang = useCallback((l: Language) => {
    setLangState(l);
    localStorage.setItem('omr_lang', l);
    document.documentElement.lang = l;
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const dict = lang === 'ar' ? ar : en;
  const t = useCallback((key: string) => dict[key] ?? key, [dict]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
